name: Update habits statistics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # Every day at 2 (UTC)

jobs:
  generate_quote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - run: pip install requests

      - run: python scripts/generate_habit_stats.py
        env:
          NOTION_ACCESS_TOKEN: ${{ secrets.NOTION_ACCESS_TOKEN }}
          QUOTES_DATABASE_ID: ${{ secrets.QUOTES_DATABASE_ID }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Habits Stats"
