name: Merge Goals

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *" # Every day at 7 (UTC)

jobs:
  merge_goals:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: python scripts/merge_goals.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: merge goals"
          commit_author: "Author <github-actions[bot]@users.noreply.github.com>"