name: Change Recent Notes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1" # Every Monday at 9 (UTC)

jobs:
  generate_recent_post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - run: pip install requests
      - run: pip install beautifulsoup4
      - run: pip install lxml

      - run: python scripts/recent_notes.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: update recent notes"
          commit_author: "Author <github-actions[bot]@users.noreply.github.com>"
